# Setting these podLabels and coredns.podLabels should ensure that vcluster
# control plane pods won't have the sidecar injected, as this is unnecessary
# for most use cases
podLabels:
  sidecar.istio.io/inject: "false"
coredns:
  podLabels:
    sidecar.istio.io/inject: "false"


# Adding the --sync-labels argument to the syncer will propagate sidecar.istio.io/inject
# label from the workloads(pods) created in the vcluster to their representation in the
# host cluster, which would allow vcluster users to control the sidecar injection
# Comment out 3 lines below to enable this, and merge this with your other syncer values
# if you have some.
# syncer:
#   extraArgs:
#     - "--sync-labels=sidecar.istio.io/inject"

#
# Warning: current configuration supports VirtualService traffic only within the same namespace.
# Traffic to service.namespace.svc(.cluster.local) URLs will not be routed by Istio.
#
---
experimental:
  multiNamespaceMode:
    enabled: true

  genericSync:
    role:
      extraRules:
        - apiGroups: ["networking.istio.io"]
          resources: ["virtualservices", "destinationrules", "serviceentries"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    # extra cluster scoper permissions required for the plugin
    clusterRole:
      extraRules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["get", "list", "watch"]
    export:
      - apiVersion: networking.istio.io/v1beta1
        kind: Gateway

      - apiVersion: networking.istio.io/v1beta1
        kind: VirtualService
        patches:
          - op: rewriteName
            path: .spec.gateways[*]
            regex: "($NAMESPACE/)?$NAME"
            conditions:
              - notEqual: "mesh"

      - apiVersion: networking.istio.io/v1beta1
        kind: DestinationRule
        patches:
          - op: rewriteName
            path: .spec.exportTo
            regex: $NAMESPACE
            conditions:
              - notEqual: "."
    import:
      - kind: Secret
        apiVersion: v1
