{{- if not .Values.headless }}
apiVersion: v1
kind: Secret
metadata:
  name: vc-{{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.globalAnnotations}}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}    
  {{- end }}
type: Opaque
stringData:
  {{- if .Values.serviceCIDR }}
  CONFIG_READY: "true"
  {{- end }}
  {{- if .Values.config }}
  config.yaml: {{ toJson .Values.config }}
  {{- else }}
  config.yaml: |-
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: Cluster
    metadata:
      name: k0s
    spec:
      api:
        port: 6443
        k0sApiPort: 9443
        extraArgs:
          enable-admission-plugins: NodeRestriction
          endpoint-reconciler-type: none
      network:
        {{- if .Values.serviceCIDR }}
        serviceCIDR: {{ .Values.serviceCIDR }}
        {{- else }}
        # Will be replaced automatically by the syncer container on first 
        serviceCIDR: CIDR_PLACEHOLDER
        {{- end }}
        provider: custom
        {{- if .Values.vcluster.clusterDomain }}
        clusterDomain: {{ .Values.vcluster.clusterDomain }}
        {{- end}}
      controllerManager:
        extraArgs:
          {{- if not .Values.sync.nodes.enableScheduler }}
          controllers: '*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle,-ttl'
          {{- else }}
          controllers: '*,-nodeipam,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle,-ttl'
          node-monitor-grace-period: 1h
          node-monitor-period: 1h
          {{- end }}
  {{- end }}
  {{- end }}