version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    target-branch: main

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
    target-branch: main

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
    target-branch: main
