version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: main

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    target-branch: main
