version: v2.7.0
name: golangci-lint
destination: ./tools

plugins:
  - module: 'github.com/loft-sh/e2e-framework/linters/defercleanupcluster'
    version: v0.0.0-20260401095027-4666f06d1a86
  - module: 'github.com/loft-sh/e2e-framework/linters/ginkgoreturnctx'
    version: v0.0.0-20260401095027-4666f06d1a86
  - module: 'github.com/loft-sh/e2e-framework/linters/defercleanupctx'
    version: v0.0.0-20260401095027-4666f06d1a86
  - module: 'github.com/loft-sh/e2e-framework/linters/describefunc'
    version: v0.0.0-20260401095027-4666f06d1a86
