run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - deadcode
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unused
    - varcheck
    - staticcheck
    - errcheck
    # - goimports
    - dupl
    - nakedret
    - stylecheck
    # - gofmt
    # - golint
    # - structcheck

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
