FROM alpine:3.16.1
RUN apk add curl
RUN curl -s -L "https://github.com/loft-sh/vcluster/releases/latest" | sed -nE 's!.*"([^"]*vcluster-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o vcluster && \
    chmod +x vcluster && mv vcluster /usr/local/bin
RUN vcluster version