# we use alpine for easier debugging
FROM alpine:3.23

# install runtime dependencies
RUN apk add --no-cache ca-certificates zstd tzdata

# Set root path as working directory
WORKDIR /

COPY vcluster .

ENTRYPOINT ["/vcluster", "start"]
