{{- if .Values.controlPlane.advanced.useConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "vc-config-{{ .Release.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.controlPlane.advanced.globalMetadata.annotations }}
  annotations:
{{ toYaml .Values.controlPlane.advanced.globalMetadata.annotations | indent 4 }}
  {{- end }}
data:
  config.yaml: {{ .Values | toYaml | quote }}
{{- end }}
