{{- if .Values.networkPolicy.ingress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-api-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: vcluster
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              vcluster.loft.sh/managed-by: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-coredns
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      vcluster.loft.sh/label-{{ .Release.Name }}-x-f0d64011ff: kube-dns
      vcluster.loft.sh/managed-by: {{ .Release.Name }}
      vcluster.loft.sh/namespace: kube-system-x-{{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: vcluster
              release: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - from:
        - podSelector:
            matchLabels:
              vcluster.loft.sh/managed-by: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
{{- end }}
