// protoc -I . pluginv2.proto  --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.3
// source: pluginv2.proto

package pluginv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Start) Reset() {
	*x = Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{0}
}

type GetClientHooks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetClientHooks) Reset() {
	*x = GetClientHooks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClientHooks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientHooks) ProtoMessage() {}

func (x *GetClientHooks) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientHooks.ProtoReflect.Descriptor instead.
func (*GetClientHooks) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{1}
}

type Mutate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Mutate) Reset() {
	*x = Mutate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutate) ProtoMessage() {}

func (x *Mutate) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutate.ProtoReflect.Descriptor instead.
func (*Mutate) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{2}
}

type SetLeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLeader) Reset() {
	*x = SetLeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLeader) ProtoMessage() {}

func (x *SetLeader) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLeader.ProtoReflect.Descriptor instead.
func (*SetLeader) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{3}
}

type Start_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualClusterConfig  string `protobuf:"bytes,1,opt,name=virtualClusterConfig,proto3" json:"virtualClusterConfig,omitempty"`
	PhysicalClusterConfig string `protobuf:"bytes,2,opt,name=physicalClusterConfig,proto3" json:"physicalClusterConfig,omitempty"`
	SyncerConfig          string `protobuf:"bytes,3,opt,name=syncerConfig,proto3" json:"syncerConfig,omitempty"`
	TargetNamespace       string `protobuf:"bytes,4,opt,name=targetNamespace,proto3" json:"targetNamespace,omitempty"`
	CurrentNamespace      string `protobuf:"bytes,5,opt,name=currentNamespace,proto3" json:"currentNamespace,omitempty"`
	Options               string `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *Start_Request) Reset() {
	*x = Start_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start_Request) ProtoMessage() {}

func (x *Start_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start_Request.ProtoReflect.Descriptor instead.
func (*Start_Request) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Start_Request) GetVirtualClusterConfig() string {
	if x != nil {
		return x.VirtualClusterConfig
	}
	return ""
}

func (x *Start_Request) GetPhysicalClusterConfig() string {
	if x != nil {
		return x.PhysicalClusterConfig
	}
	return ""
}

func (x *Start_Request) GetSyncerConfig() string {
	if x != nil {
		return x.SyncerConfig
	}
	return ""
}

func (x *Start_Request) GetTargetNamespace() string {
	if x != nil {
		return x.TargetNamespace
	}
	return ""
}

func (x *Start_Request) GetCurrentNamespace() string {
	if x != nil {
		return x.CurrentNamespace
	}
	return ""
}

func (x *Start_Request) GetOptions() string {
	if x != nil {
		return x.Options
	}
	return ""
}

type Start_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Start_Response) Reset() {
	*x = Start_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Start_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start_Response) ProtoMessage() {}

func (x *Start_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start_Response.ProtoReflect.Descriptor instead.
func (*Start_Response) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{0, 1}
}

type GetClientHooks_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetClientHooks_Request) Reset() {
	*x = GetClientHooks_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClientHooks_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientHooks_Request) ProtoMessage() {}

func (x *GetClientHooks_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientHooks_Request.ProtoReflect.Descriptor instead.
func (*GetClientHooks_Request) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{1, 0}
}

type GetClientHooks_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientHooks []*GetClientHooks_ClientHook `protobuf:"bytes,1,rep,name=clientHooks,proto3" json:"clientHooks,omitempty"`
}

func (x *GetClientHooks_Response) Reset() {
	*x = GetClientHooks_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClientHooks_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientHooks_Response) ProtoMessage() {}

func (x *GetClientHooks_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientHooks_Response.ProtoReflect.Descriptor instead.
func (*GetClientHooks_Response) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetClientHooks_Response) GetClientHooks() []*GetClientHooks_ClientHook {
	if x != nil {
		return x.ClientHooks
	}
	return nil
}

type GetClientHooks_ClientHook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string   `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind       string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Types      []string `protobuf:"bytes,3,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *GetClientHooks_ClientHook) Reset() {
	*x = GetClientHooks_ClientHook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetClientHooks_ClientHook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientHooks_ClientHook) ProtoMessage() {}

func (x *GetClientHooks_ClientHook) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientHooks_ClientHook.ProtoReflect.Descriptor instead.
func (*GetClientHooks_ClientHook) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{1, 2}
}

func (x *GetClientHooks_ClientHook) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetClientHooks_ClientHook) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GetClientHooks_ClientHook) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

type Mutate_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind       string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Object     string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Mutate_Request) Reset() {
	*x = Mutate_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutate_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutate_Request) ProtoMessage() {}

func (x *Mutate_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutate_Request.ProtoReflect.Descriptor instead.
func (*Mutate_Request) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Mutate_Request) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Mutate_Request) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Mutate_Request) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *Mutate_Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Mutate_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object  string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Mutated bool   `protobuf:"varint,2,opt,name=mutated,proto3" json:"mutated,omitempty"`
}

func (x *Mutate_Response) Reset() {
	*x = Mutate_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutate_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutate_Response) ProtoMessage() {}

func (x *Mutate_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutate_Response.ProtoReflect.Descriptor instead.
func (*Mutate_Response) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Mutate_Response) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *Mutate_Response) GetMutated() bool {
	if x != nil {
		return x.Mutated
	}
	return false
}

type SetLeader_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLeader_Request) Reset() {
	*x = SetLeader_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLeader_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLeader_Request) ProtoMessage() {}

func (x *SetLeader_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLeader_Request.ProtoReflect.Descriptor instead.
func (*SetLeader_Request) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{3, 0}
}

type SetLeader_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLeader_Response) Reset() {
	*x = SetLeader_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLeader_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLeader_Response) ProtoMessage() {}

func (x *SetLeader_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLeader_Response.ProtoReflect.Descriptor instead.
func (*SetLeader_Response) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{3, 1}
}

var File_pluginv2_proto protoreflect.FileDescriptor

var file_pluginv2_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x22, 0x9d, 0x02, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x1a, 0x87, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x32, 0x0a, 0x14, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14,
	0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x34, 0x0a, 0x15, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c,
	0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x15, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x79,
	0x6e, 0x63, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x73, 0x79, 0x6e, 0x63, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x28,
	0x0a, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x0a,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc6, 0x01, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x1a, 0x09, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x51, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6f,
	0x6f, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x76, 0x32, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6f,
	0x6f, 0x6b, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x52, 0x0b,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x1a, 0x56, 0x0a, 0x0a, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x69,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x06, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x69,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x69,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61,
	0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x6d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x64, 0x22, 0x22, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa2, 0x02, 0x0a, 0x06,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x3a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12,
	0x17, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48,
	0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x73, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76,
	0x32, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6f, 0x6f, 0x6b, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x4d, 0x75, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x4d,
	0x75, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32,
	0x2e, 0x53, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x53, 0x65,
	0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x6f, 0x66, 0x74, 0x2d, 0x73, 0x68, 0x2f, 0x76, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pluginv2_proto_rawDescOnce sync.Once
	file_pluginv2_proto_rawDescData = file_pluginv2_proto_rawDesc
)

func file_pluginv2_proto_rawDescGZIP() []byte {
	file_pluginv2_proto_rawDescOnce.Do(func() {
		file_pluginv2_proto_rawDescData = protoimpl.X.CompressGZIP(file_pluginv2_proto_rawDescData)
	})
	return file_pluginv2_proto_rawDescData
}

var file_pluginv2_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pluginv2_proto_goTypes = []interface{}{
	(*Start)(nil),                     // 0: pluginv2.Start
	(*GetClientHooks)(nil),            // 1: pluginv2.GetClientHooks
	(*Mutate)(nil),                    // 2: pluginv2.Mutate
	(*SetLeader)(nil),                 // 3: pluginv2.SetLeader
	(*Start_Request)(nil),             // 4: pluginv2.Start.Request
	(*Start_Response)(nil),            // 5: pluginv2.Start.Response
	(*GetClientHooks_Request)(nil),    // 6: pluginv2.GetClientHooks.Request
	(*GetClientHooks_Response)(nil),   // 7: pluginv2.GetClientHooks.Response
	(*GetClientHooks_ClientHook)(nil), // 8: pluginv2.GetClientHooks.ClientHook
	(*Mutate_Request)(nil),            // 9: pluginv2.Mutate.Request
	(*Mutate_Response)(nil),           // 10: pluginv2.Mutate.Response
	(*SetLeader_Request)(nil),         // 11: pluginv2.SetLeader.Request
	(*SetLeader_Response)(nil),        // 12: pluginv2.SetLeader.Response
}
var file_pluginv2_proto_depIdxs = []int32{
	8,  // 0: pluginv2.GetClientHooks.Response.clientHooks:type_name -> pluginv2.GetClientHooks.ClientHook
	4,  // 1: pluginv2.Plugin.Start:input_type -> pluginv2.Start.Request
	6,  // 2: pluginv2.Plugin.GetClientHooks:input_type -> pluginv2.GetClientHooks.Request
	9,  // 3: pluginv2.Plugin.Mutate:input_type -> pluginv2.Mutate.Request
	11, // 4: pluginv2.Plugin.SetLeader:input_type -> pluginv2.SetLeader.Request
	5,  // 5: pluginv2.Plugin.Start:output_type -> pluginv2.Start.Response
	7,  // 6: pluginv2.Plugin.GetClientHooks:output_type -> pluginv2.GetClientHooks.Response
	10, // 7: pluginv2.Plugin.Mutate:output_type -> pluginv2.Mutate.Response
	12, // 8: pluginv2.Plugin.SetLeader:output_type -> pluginv2.SetLeader.Response
	5,  // [5:9] is the sub-list for method output_type
	1,  // [1:5] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_pluginv2_proto_init() }
func file_pluginv2_proto_init() {
	if File_pluginv2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pluginv2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClientHooks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mutate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Start_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClientHooks_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClientHooks_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetClientHooks_ClientHook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mutate_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mutate_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLeader_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLeader_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pluginv2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginv2_proto_goTypes,
		DependencyIndexes: file_pluginv2_proto_depIdxs,
		MessageInfos:      file_pluginv2_proto_msgTypes,
	}.Build()
	File_pluginv2_proto = out.File
	file_pluginv2_proto_rawDesc = nil
	file_pluginv2_proto_goTypes = nil
	file_pluginv2_proto_depIdxs = nil
}
