// protoc -I . pluginv2.proto  --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: pluginv2.proto

package pluginv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Initialize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Initialize) Reset() {
	*x = Initialize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Initialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initialize) ProtoMessage() {}

func (x *Initialize) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initialize.ProtoReflect.Descriptor instead.
func (*Initialize) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{0}
}

type GetPluginConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginConfig) Reset() {
	*x = GetPluginConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginConfig) ProtoMessage() {}

func (x *GetPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginConfig.ProtoReflect.Descriptor instead.
func (*GetPluginConfig) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{1}
}

type Mutate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Mutate) Reset() {
	*x = Mutate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutate) ProtoMessage() {}

func (x *Mutate) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutate.ProtoReflect.Descriptor instead.
func (*Mutate) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{2}
}

type SetLeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLeader) Reset() {
	*x = SetLeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLeader) ProtoMessage() {}

func (x *SetLeader) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLeader.ProtoReflect.Descriptor instead.
func (*SetLeader) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{3}
}

type Initialize_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *Initialize_Request) Reset() {
	*x = Initialize_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Initialize_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initialize_Request) ProtoMessage() {}

func (x *Initialize_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initialize_Request.ProtoReflect.Descriptor instead.
func (*Initialize_Request) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Initialize_Request) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type Initialize_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Initialize_Response) Reset() {
	*x = Initialize_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Initialize_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Initialize_Response) ProtoMessage() {}

func (x *Initialize_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Initialize_Response.ProtoReflect.Descriptor instead.
func (*Initialize_Response) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{0, 1}
}

type GetPluginConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPluginConfig_Request) Reset() {
	*x = GetPluginConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginConfig_Request) ProtoMessage() {}

func (x *GetPluginConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginConfig_Request.ProtoReflect.Descriptor instead.
func (*GetPluginConfig_Request) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{1, 0}
}

type GetPluginConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config string `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *GetPluginConfig_Response) Reset() {
	*x = GetPluginConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPluginConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPluginConfig_Response) ProtoMessage() {}

func (x *GetPluginConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPluginConfig_Response.ProtoReflect.Descriptor instead.
func (*GetPluginConfig_Response) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetPluginConfig_Response) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type Mutate_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion string `protobuf:"bytes,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Kind       string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Object     string `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Mutate_Request) Reset() {
	*x = Mutate_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutate_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutate_Request) ProtoMessage() {}

func (x *Mutate_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutate_Request.ProtoReflect.Descriptor instead.
func (*Mutate_Request) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Mutate_Request) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Mutate_Request) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Mutate_Request) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *Mutate_Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Mutate_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object  string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Mutated bool   `protobuf:"varint,2,opt,name=mutated,proto3" json:"mutated,omitempty"`
}

func (x *Mutate_Response) Reset() {
	*x = Mutate_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutate_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutate_Response) ProtoMessage() {}

func (x *Mutate_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutate_Response.ProtoReflect.Descriptor instead.
func (*Mutate_Response) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Mutate_Response) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *Mutate_Response) GetMutated() bool {
	if x != nil {
		return x.Mutated
	}
	return false
}

type SetLeader_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLeader_Request) Reset() {
	*x = SetLeader_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLeader_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLeader_Request) ProtoMessage() {}

func (x *SetLeader_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLeader_Request.ProtoReflect.Descriptor instead.
func (*SetLeader_Request) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{3, 0}
}

type SetLeader_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetLeader_Response) Reset() {
	*x = SetLeader_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pluginv2_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLeader_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLeader_Response) ProtoMessage() {}

func (x *SetLeader_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pluginv2_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLeader_Response.ProtoReflect.Descriptor instead.
func (*SetLeader_Response) Descriptor() ([]byte, []int) {
	return file_pluginv2_proto_rawDescGZIP(), []int{3, 1}
}

var File_pluginv2_proto protoreflect.FileDescriptor

var file_pluginv2_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x22, 0x3b, 0x0a, 0x0a, 0x49, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x0a, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xb1, 0x01, 0x0a, 0x06, 0x4d, 0x75,
	0x74, 0x61, 0x74, 0x65, 0x1a, 0x69, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a,
	0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x64, 0x22, 0x22, 0x0a,
	0x09, 0x53, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xb4, 0x02, 0x0a, 0x06, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x49, 0x0a, 0x0a,
	0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x76, 0x32, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e,
	0x53, 0x65, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x53, 0x65, 0x74,
	0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x21, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x4d, 0x75, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x4d,
	0x75, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x2e, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x65, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6f, 0x66, 0x74, 0x2d, 0x73, 0x68, 0x2f, 0x76,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x32, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pluginv2_proto_rawDescOnce sync.Once
	file_pluginv2_proto_rawDescData = file_pluginv2_proto_rawDesc
)

func file_pluginv2_proto_rawDescGZIP() []byte {
	file_pluginv2_proto_rawDescOnce.Do(func() {
		file_pluginv2_proto_rawDescData = protoimpl.X.CompressGZIP(file_pluginv2_proto_rawDescData)
	})
	return file_pluginv2_proto_rawDescData
}

var file_pluginv2_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pluginv2_proto_goTypes = []interface{}{
	(*Initialize)(nil),               // 0: pluginv2.Initialize
	(*GetPluginConfig)(nil),          // 1: pluginv2.GetPluginConfig
	(*Mutate)(nil),                   // 2: pluginv2.Mutate
	(*SetLeader)(nil),                // 3: pluginv2.SetLeader
	(*Initialize_Request)(nil),       // 4: pluginv2.Initialize.Request
	(*Initialize_Response)(nil),      // 5: pluginv2.Initialize.Response
	(*GetPluginConfig_Request)(nil),  // 6: pluginv2.GetPluginConfig.Request
	(*GetPluginConfig_Response)(nil), // 7: pluginv2.GetPluginConfig.Response
	(*Mutate_Request)(nil),           // 8: pluginv2.Mutate.Request
	(*Mutate_Response)(nil),          // 9: pluginv2.Mutate.Response
	(*SetLeader_Request)(nil),        // 10: pluginv2.SetLeader.Request
	(*SetLeader_Response)(nil),       // 11: pluginv2.SetLeader.Response
}
var file_pluginv2_proto_depIdxs = []int32{
	4,  // 0: pluginv2.Plugin.Initialize:input_type -> pluginv2.Initialize.Request
	10, // 1: pluginv2.Plugin.SetLeader:input_type -> pluginv2.SetLeader.Request
	6,  // 2: pluginv2.Plugin.GetPluginConfig:input_type -> pluginv2.GetPluginConfig.Request
	8,  // 3: pluginv2.Plugin.Mutate:input_type -> pluginv2.Mutate.Request
	5,  // 4: pluginv2.Plugin.Initialize:output_type -> pluginv2.Initialize.Response
	11, // 5: pluginv2.Plugin.SetLeader:output_type -> pluginv2.SetLeader.Response
	7,  // 6: pluginv2.Plugin.GetPluginConfig:output_type -> pluginv2.GetPluginConfig.Response
	9,  // 7: pluginv2.Plugin.Mutate:output_type -> pluginv2.Mutate.Response
	4,  // [4:8] is the sub-list for method output_type
	0,  // [0:4] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_pluginv2_proto_init() }
func file_pluginv2_proto_init() {
	if File_pluginv2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pluginv2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Initialize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mutate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Initialize_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Initialize_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPluginConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mutate_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mutate_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLeader_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pluginv2_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLeader_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pluginv2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluginv2_proto_goTypes,
		DependencyIndexes: file_pluginv2_proto_depIdxs,
		MessageInfos:      file_pluginv2_proto_msgTypes,
	}.Build()
	File_pluginv2_proto = out.File
	file_pluginv2_proto_rawDesc = nil
	file_pluginv2_proto_goTypes = nil
	file_pluginv2_proto_depIdxs = nil
}
