{{- if and .Values.isolation.enabled .Values.isolation.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name:  {{ template "vcluster.name" . }}-quota
  namespace: {{ .Values.isolation.namespace | default .Release.Namespace }}
spec:
  hard:
    {{- range $key, $val := .Values.isolation.resourceQuota.quota }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}

  {{- if .Values.isolation.resourceQuota.scopeSelector.matchExpressions }}
  scopeSelector:
    matchExpressions:
     {{- toYaml .Values.isolation.resourceQuota.scopeSelector.matchExpressions | nindent 4 }}
  {{- end}}

  {{- if .Values.isolation.resourceQuota.scopes }}
  scopes:
    {{- toYaml .Values.isolation.resourceQuota.scopes | nindent 4 }}
  {{- end}}

{{- end }}
