{{- if not .Values.headless }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.syncer.labels }}
{{ toYaml .Values.syncer.labels | indent 4 }}
{{- end }}
  {{- $annotations := merge .Values.globalAnnotations .Values.syncer.annotations }}
  {{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.syncer.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      {{- if (eq (int .Values.syncer.replicas) 1) }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: vcluster
      release: {{ .Release.Name }}
  template:
    metadata:
  {{- if .Values.syncer.podAnnotations }}
      annotations:
{{ toYaml .Values.syncer.podAnnotations | indent 8 }}
  {{- end }}
      labels:
        app: vcluster
        release: {{ .Release.Name }}
      {{- range $k, $v := .Values.syncer.podLabels }}
        {{ $k }}: {{ $v | quote }}
      {{- end }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- if .Values.syncer.affinity }}
      affinity:
{{ toYaml .Values.syncer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.syncer.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.syncer.topologySpreadConstraints | indent 8 }}
      {{- end }}
      nodeSelector:
{{ toYaml .Values.syncer.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.syncer.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.syncer.tolerations | indent 8 }}
      {{- if .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- else }}
      serviceAccountName: vc-{{ .Release.Name }}
      {{- end }}
      {{- if .Values.syncer.podSecurityContext }}
      securityContext:
{{ toYaml .Values.syncer.podSecurityContext | indent 8 }}
      {{- end }}
      volumes:
      {{- if or .Values.syncer.securityContext.runAsUser .Values.syncer.securityContext.runAsNonRoot }}
        - name: helm-cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      {{- end }}
        - name: certs
          secret:
            secretName: {{ .Release.Name }}-certs
      {{- if .Values.syncer.volumes }}
{{ toYaml .Values.syncer.volumes | indent 8 }}
      {{- end }}
      {{- if .Values.coredns.enabled }}
        - name: coredns
          configMap:
            name: {{ .Release.Name }}-coredns
      {{- end }}
        - name: custom-config-volume
          configMap:
            name: coredns-custom
            optional: true
      {{- if .Values.syncer.priorityClassName }}
      priorityClassName: {{ .Values.syncer.priorityClassName }}
      {{- end }}
      containers:
      - name: syncer
        {{- if .Values.syncer.image }}
        image: "{{ .Values.defaultImageRegistry }}{{ .Values.syncer.image }}"
        {{- else }}
        image: "{{ .Values.defaultImageRegistry }}ghcr.io/loft-sh/vcluster:{{ .Chart.Version }}"
        {{- end }}
        {{- if .Values.syncer.workingDir }}
        workingDir: {{ .Values.syncer.workingDir }}
        {{- end }}
        {{- if .Values.syncer.command }}
        command:
        {{- range $f := .Values.syncer.command }}
        - {{ $f | quote }}
        {{- end }}
        {{- end }}
        {{- if not .Values.syncer.noArgs }}
        args:
          - --name={{ .Release.Name }}
          - --request-header-ca-cert=/pki/ca.crt
          - --client-ca-cert=/pki/ca.crt
          - --server-ca-cert=/pki/ca.crt
          - --server-ca-key=/pki/ca.key
          - --kube-config=/pki/admin.conf
          - --service-account=vc-workload-{{ .Release.Name }}
          {{- range $key, $container := .Values.plugin }}
          {{- if not $container.optional }}
          - --plugins={{ $key }}
          {{- end }}
          {{- end }}
          {{- include "vcluster.serviceMapping.fromHost" . | indent 10 }}
          {{- include "vcluster.serviceMapping.fromVirtual" . | indent 10 }}
          {{- if .Values.defaultImageRegistry }}
          - --default-image-registry={{ .Values.defaultImageRegistry }}
          {{- end }}
          {{- if .Values.syncer.kubeConfigContextName }}
          - --kube-config-context-name={{ .Values.syncer.kubeConfigContextName }}
          {{- end }}
          {{- if .Values.enableHA }}
          - --leader-elect=true
          {{- else }}
          - --leader-elect=false
          {{- end }}
          {{- if .Values.ingress.enabled }}
          - --tls-san={{ .Values.ingress.host }}
          {{- end }}
          {{- include "vcluster.syncer.syncArgs" . | indent 10 -}}
          {{- if .Values.sync.nodes.syncAllNodes }}
          - --sync-all-nodes
          {{- end }}
          {{- if .Values.isolation.enabled }}
          - --enforce-pod-security-standard={{ .Values.isolation.podSecurityStandard }}
          {{- end}}
          {{- if .Values.sync.nodes.nodeSelector }}
          - --node-selector={{ .Values.sync.nodes.nodeSelector }}
          {{- end }}
          {{- if .Values.multiNamespaceMode.enabled }}
          - --multi-namespace-mode=true
          {{- end }}
          {{- if .Values.sync.configmaps.all }}
          - --sync-all-configmaps=true
          {{- end }}
          {{- if .Values.sync.secrets.all }}
          - --sync-all-secrets=true
          {{- end }}
          {{- if not .Values.sync.nodes.fakeKubeletIPs }}
          - --fake-kubelet-ips=false
          {{- end }}
          {{- if or .Values.proxy.metricsServer.nodes.enabled .Values.proxy.metricsServer.pods.enabled}}
          - --proxy-metrics-server=true
          {{- end }}
          {{- range $f := .Values.syncer.extraArgs }}
          - {{ $f | quote }}
          {{- end }}
        {{- else }}
        args:
{{ toYaml .Values.syncer.extraArgs | indent 10 }}
        {{- end }}
        {{- if .Values.syncer.livenessProbe }}
        {{- if .Values.syncer.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 2
        {{- end }}
        {{- end }}
        {{- if .Values.syncer.readinessProbe }}
        {{- if .Values.syncer.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8443
            scheme: HTTPS
          failureThreshold: 30
          periodSeconds: 2
        {{- end }}
        {{- end }}
        securityContext:
{{ toYaml .Values.syncer.securityContext | indent 10 }}
        env:
        {{- if eq (.Values.syncer.replicas | toString | atoi) 1 }}
          - name: VCLUSTER_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        {{- end }}
        {{- if .Values.syncer.env }}
{{ toYaml .Values.syncer.env | indent 10 }}
        {{- end }}
        {{- if .Values.sync.generic.config }}
          - name: CONFIG
            value: |-
              {{- .Values.sync.generic.config | nindent 14 }}
        {{- end }}
          - name: VCLUSTER_TELEMETRY_CONFIG
            value: {{ .Values.telemetry | toJson | quote }}
        volumeMounts:
        {{- if or .Values.syncer.securityContext.runAsUser .Values.syncer.securityContext.runAsNonRoot }}
          - name: helm-cache
            mountPath: /.cache/helm
          - name: tmp
            mountPath: /tmp
        {{- end }}
{{ toYaml .Values.syncer.volumeMounts | indent 10 }}
        {{- if .Values.syncer.extraVolumeMounts }}
{{ toYaml .Values.syncer.extraVolumeMounts | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.syncer.resources | indent 10 }}
      {{- $counter := -1 -}}
      {{- range $key, $container := .Values.plugin }}
      {{- $counter = add1 $counter }}
      - image: {{ $.Values.defaultImageRegistry }}{{ $container.image }}
        {{- if $container.name }}
        name: {{ $container.name | quote }}
        {{- else }}
        name: {{ $key | quote }}
        {{- end }}
        {{- if $container.imagePullPolicy }}
        imagePullPolicy: {{ $container.imagePullPolicy }}
        {{- end }}
        {{- if $container.workingDir }}
        workingDir: {{ $container.workingDir }}
        {{- end }}
        {{- if $container.command }}
        command:
          {{- range $commandIndex, $command := $container.command }}
          - {{ $command | quote }}
          {{- end }}
        {{- end }}
        {{- if $container.args }}
        args:
          {{- range $argIndex, $arg := $container.args }}
          - {{ $arg | quote }}
          {{- end }}
        {{- end }}
        {{- if $container.terminationMessagePath }}
        terminationMessagePath: {{ $container.terminationMessagePath }}
        {{- end }}
        {{- if $container.terminationMessagePolicy }}
        terminationMessagePolicy: {{ $container.terminationMessagePolicy }}
        {{- end }}
        env:
          - name: VCLUSTER_PLUGIN_ADDRESS
            value: "localhost:{{ add 14000 $counter }}"
          - name: VCLUSTER_PLUGIN_NAME
            value: "{{ $key }}"
        {{- if $container.env }}
{{ toYaml $container.env | indent 10 }}
        {{- end }}
        envFrom:
{{ toYaml $container.envFrom | indent 10 }}
        securityContext:
{{ toYaml $container.securityContext | indent 10 }}
        lifecycle:
{{ toYaml $container.lifecycle | indent 10 }}
        livenessProbe:
{{ toYaml $container.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml $container.readinessProbe | indent 10 }}
        startupProbe:
{{ toYaml $container.startupProbe | indent 10 }}
        volumeDevices:
{{ toYaml $container.volumeDevices | indent 10 }}
        volumeMounts:
{{ toYaml $container.volumeMounts | indent 10 }}
        {{- if $container.resources }}
        resources:
{{ toYaml $container.resources | indent 10 }}
        {{- end }}
        {{- end }}
{{- end }}
