multiNamespaceMode:
  enabled: true
sync:
  generic:
    role:
      extraRules:
        - apiGroups: ["karpenter.sh"]
          resources: ["provisioners"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
        - apiGroups: ["karpenter.k8s.aws"]
          resources: ["awsnodetemplates"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    clusterRole:
      extraRules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["get", "list", "watch"]
    config: |-
      version: v1beta1
      export:
        - apiVersion: karpenter.sh/v1alpha5
          kind: Provisioner
        - apiVersion: karpenter.k8s.aws/v1alpha1
          kind: AWSNodeTemplate
          