sync:
  toHost:
    customResources:
      awsnodetemplates.karpenter.k8s.aws:
        enabled: true
      provisioners.karpenter.sh:
        enabled: true

experimental:
  multiNamespaceMode:
    enabled: true
