# NOTE: This config was created with Traefik version v2.9.10 (the version currently shipping with K3s).
experimental:
  multiNamespaceMode:
    enabled: true

  genericSync:
    role:
      extraRules:
        # NOTE: If your host cluster uses Traefik v3+, you will need to change "traefik.containo.us" to "traefik.io".
        - apiGroups: ["traefik.containo.us"]
          # TODO: Add support for more than just these ingress types.
          resources: ["ingressroutes", "ingressroutetcps", "ingressrouteudps"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    clusterRole:
      extraRules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["get", "list", "watch"]
    export:
      - apiVersion: traefik.containo.us/v1alpha1
        kind: IngressRoute
      - apiVersion: traefik.containo.us/v1alpha1
        kind: IngressRouteTCP
      - apiVersion: traefik.containo.us/v1alpha1
        kind: IngressRouteUDP
