sync:
  toHost:
    customResources:
      ingressroutes.traefik.io:
        enabled: true
      ingressroutetcps.traefik.io:
        enabled: true
      ingressrouteudps.traefik.io:
        enabled: true

experimental:
  multiNamespaceMode:
    enabled: true
