{{- if .Values.coredns.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vcluster.name" . }}-coredns
  namespace: {{ .Release.Namespace }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}
  {{- end }}
data:
{{- if .Values.coredns.manifests }}
  coredns.yaml: |-
{{ .Values.coredns.manifests | indent 4 }}
{{- else }}
  coredns.yaml: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: coredns
      namespace: kube-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        kubernetes.io/bootstrapping: rbac-defaults
      name: system:coredns
    rules:
      - apiGroups:
          - ""
        resources:
          - endpoints
          - services
          - pods
          - namespaces
        verbs:
          - list
          - watch
      - apiGroups:
          - discovery.k8s.io
        resources:
          - endpointslices
        verbs:
          - list
          - watch
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      annotations:
        rbac.authorization.kubernetes.io/autoupdate: "true"
      labels:
        kubernetes.io/bootstrapping: rbac-defaults
      name: system:coredns
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:coredns
    subjects:
      - kind: ServiceAccount
        name: coredns
        namespace: kube-system
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: coredns
      namespace: kube-system
    data:
      Corefile: |
        {{- if .Values.coredns.config }}
{{ .Values.coredns.config | indent 8 }}
        {{- else }}
        .:1053 {
            {{`{{.LOG_IN_DEBUG}}`}}
            errors
            health
            ready
            rewrite name regex .*\.nodes\.vcluster\.com kubernetes.default.svc.cluster.local
            kubernetes cluster.local in-addr.arpa ip6.arpa { 
              pods insecure
              {{- if .Values.fallbackHostDns }}
              fallthrough cluster.local in-addr.arpa ip6.arpa
              {{- else }}
              fallthrough in-addr.arpa ip6.arpa
              {{- end }}
            }
            hosts /etc/coredns/NodeHosts {
              ttl 60
              reload 15s
              fallthrough
            }
            prometheus :9153
            {{- if .Values.fallbackHostDns }}
            forward . {{`{{.HOST_CLUSTER_DNS}}`}}
            {{- else if and .Values.isolation.enabled  .Values.isolation.networkPolicy.enabled }}
            forward . /etc/resolv.conf 8.8.8.8 {
              policy sequential
            }
            {{- else }}
            forward . /etc/resolv.conf
            {{- end }}
            cache 30
            loop
            reload
            loadbalance
        }

        import /etc/coredns/custom/*.server
        {{- end }}
      NodeHosts: ""
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: coredns
      namespace: kube-system
      labels:
        k8s-app: kube-dns
        kubernetes.io/name: "CoreDNS"
    spec:
      replicas: {{ .Values.coredns.replicas }}
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
      selector:
        matchLabels:
          k8s-app: kube-dns
      template:
        metadata:
  {{- if .Values.coredns.podAnnotations }}
          annotations:
{{ toYaml .Values.coredns.podAnnotations | indent 12 }}
  {{- end }}
          labels:
            k8s-app: kube-dns
          {{- range $k, $v := .Values.coredns.podLabels }}
            {{ $k }}: {{ $v | quote }}
          {{- end }}
        spec:
          priorityClassName: "system-cluster-critical"
          serviceAccountName: coredns
          nodeSelector:
            kubernetes.io/os: linux
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  k8s-app: kube-dns
          {{- if .Values.isolation.enabled }}
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          {{- end }}
          containers:
            - name: coredns
              {{- if .Values.coredns.image }}
              image: {{ .Values.coredns.image }}
              {{- else }}
              image: {{`{{.IMAGE}}`}}
              {{- end }}
              imagePullPolicy: IfNotPresent
              resources:
{{ toYaml .Values.coredns.resources | indent 16}}
              args: [ "-conf", "/etc/coredns/Corefile" ]
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/coredns
                  readOnly: true
                - name: custom-config-volume
                  mountPath: /etc/coredns/custom
                  readOnly: true
              ports:
                - containerPort: 1053
                  name: dns
                  protocol: UDP
                - containerPort: 1053
                  name: dns-tcp
                  protocol: TCP
                - containerPort: 9153
                  name: metrics
                  protocol: TCP
              securityContext:
                runAsNonRoot: true
                runAsUser: {{`{{.RUN_AS_USER}}`}}
                runAsGroup: {{`{{.RUN_AS_GROUP}}`}}
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                periodSeconds: 10
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /ready
                  port: 8181
                  scheme: HTTP
                initialDelaySeconds: 0
                periodSeconds: 2
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 3
          dnsPolicy: Default
          volumes:
            - name: config-volume
              configMap:
                name: coredns
                items:
                  - key: Corefile
                    path: Corefile
                  - key: NodeHosts
                    path: NodeHosts
            - name: custom-config-volume
              configMap:
                name: coredns-custom
                optional: true
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: kube-dns
      namespace: kube-system
      annotations:
        prometheus.io/port: "9153"
        prometheus.io/scrape: "true"
        {{- if .Values.coredns.service.annotations }}
{{ toYaml .Values.coredns.service.annotations | indent 8 }}
        {{- end }}
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
        kubernetes.io/name: "CoreDNS"
    spec:
      selector:
        k8s-app: kube-dns
      type: {{ .Values.coredns.service.type }}
      {{- if (eq (.Values.coredns.service.type) "LoadBalancer") }}
      {{- if .Values.coredns.service.externalTrafficPolicy }}
      externalTrafficPolicy: {{ .Values.coredns.service.externalTrafficPolicy }}
      {{- end }}
      {{- if .Values.coredns.service.externalIPs }}
      externalIPs:
        {{- range $f := .Values.coredns.service.externalIPs }}
        - {{ $f }}
        {{- end }}
      {{- end }}
      {{- end }}
      ports:
        - name: dns
          port: 53
          targetPort: 1053
          protocol: UDP
        - name: dns-tcp
          port: 53
          targetPort: 1053
          protocol: TCP
        - name: metrics
          port: 9153
          protocol: TCP
{{- end }}
{{- end }}
