{{- if (and (.Values.enableHA) (not .Values.serverToken.secretKeyRef)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcluster.k3s.tokenSecretName" . | quote }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "3"
    # helm.sh/hook-delete-policy: before-hook-creation # Default value
    helm.sh/resource-policy: keep
type: Opaque
data:
{{- if .Values.serverToken.value }}
  server-token: {{ .Values.serverToken.value | b64enc | quote }}
{{- else }}
  server-token: {{ (randAlphaNum 32) | b64enc | quote }}
{{- end }}
{{- end }}
