{{- if (and (.Values.enableHA) (not .Values.serverToken.secretKeyRef)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.serverToken.value }}
  server-token: {{ .Values.serverToken.value | b64enc | quote }}
{{- else }}
  server-token: {{ include "vcluster.k3s.serverToken" . }}
{{- end }}
{{- end }}
