{{- if not .Values.headless }}
{{- if (eq (include "vcluster.k3s.workloadKind" .) "StatefulSet") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "vcluster.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- $annotations := merge .Values.globalAnnotations .Values.syncer.serviceAnnotations }}
  {{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
  {{- end }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  clusterIP: None
  selector:
    app: vcluster
    release: "{{ .Release.Name }}"
{{- end }}
{{- end }}