sync:
  toHost:
    customResources:
      tasks.tekton.dev:
        enabled: true
      taskruns.tekton.dev:
        enabled: true
      pipelines.tekton.dev:
        enabled: true
      pipelineruns.tekton.dev:
        enabled: true

experimental:
  multiNamespaceMode:
    enabled: true
