experimental:
  multiNamespaceMode:
    enabled: true

  genericSync:
    role:
      extraRules:
        - apiGroups: ["tekton.dev"]
          resources: ["tasks", "taskruns", "pipelines", "pipelineruns"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    export:
      - apiVersion: tekton.dev/v1beta1
        kind: Task
      - apiVersion: tekton.dev/v1beta1
        kind: TaskRun
        patches:
          - op: rewriteName
            path: spec.taskRef.name
      - apiVersion: tekton.dev/v1beta1
        kind: Pipeline
        patches:
          - op: rewriteName
            path: spec.tasks[*].taskRef.name
          - op: rewriteName
            path: spec.resources[*].name
          - op: rewriteName
            path: spec.results[*].name
      - apiVersion: tekton.dev/v1beta1
        kind: PipelineRun
        patches:
          - op: rewriteName
            path: spec.pipelineRef.name
