experimental:
  multiNamespaceMode:
    # if you disable this, make sure to add the relevant references to the custom resources below
    enabled: true

sync:
  toHost:
    secrets:
      all: true
    customResources:
      issuers.cert-manager.io:
        enabled: true
      certificates.cert-manager.io:
        enabled: true
