controlPlane:
  statefulSet:
    image:
      registry: ""
      repository: {{ .Repository }}
      tag: {{ .Tag }}
exportKubeConfig:
  additionalSecrets:
    - name: export-kubeconfig-same-ns
      server: "https://export-kubeconfig-vcluster.vcluster-export-kubeconfig-vcluster.svc:443"
      context: same-ns-context
    - name: export-kubeconfig-cross-ns
      namespace: export-kubeconfig-target
      server: "https://export-kubeconfig-vcluster.export-kubeconfig-target.svc:443"
      context: cross-ns-context
