experimental:
  multiNamespaceMode:
    enabled: true

  genericSync:
    role:
      extraRules:
        - apiGroups: ["serving.knative.dev"]
          resources: ["services", "configurations", "revisions", "routes"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    clusterRole:
      extraRules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["get", "list", "watch"]
    export:
      - apiVersion: serving.knative.dev/v1
        kind: Service
      - apiVersion: serving.knative.dev/v1
        kind: Configuration
      - apiVersion: serving.knative.dev/v1
        kind: Revision
      - apiVersion: serving.knative.dev/v1
        kind: Route
    import:
      - apiVersion: serving.knative.dev/v1
        kind: Service
      - apiVersion: serving.knative.dev/v1
        kind: Configuration
      - apiVersion: serving.knative.dev/v1
        kind: Revision
      - apiVersion: serving.knative.dev/v1
        kind: Route
