sync:
  toHost:
    customResources:
      services.serving.knative.dev:
        enabled: true
      configurations.serving.knative.dev:
        enabled: true
      revisions.serving.knative.dev:
        enabled: true
      routes.serving.knative.dev:
        enabled: true

experimental:
  multiNamespaceMode:
    enabled: true
