syncer:
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"

vcluster:
  env:
  - name: K3S_DATASTORE_ENDPOINT
    value: mysql://root:my-password@tcp(mysql:3306)/k3s
  resources:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"