#!/bin/bash
list="images.txt"
images="vcluster-images.tar.gz"
platforms="linux/amd64"

usage () {
    echo "USAGE: $0 [--image-list images.txt] [--images vcluster-images.tar.gz]"
    echo "  [-l|--image-list path] text file with list of images; one image per line."
    echo "  [-i|--images path] tar.gz generated by docker save."
    echo "  [-p|--platforms platforms] comma-separated platforms to download. (Default: linux/amd64)"
    echo "  [-h|--help] Usage message"
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -i|--images)
        images="$2"
        shift # past argument
        shift # past value
        ;;
        -l|--image-list)
        list="$2"
        shift # past argument
        shift # past value
        ;;
        -p|--platforms)
        platforms="$2"
        shift # past argument
        shift # past value
        ;;
        -h|--help)
        help="true"
        shift
        ;;
        *)
        usage
        exit 1
        ;;
    esac
done

if [[ $help ]]; then
    usage
    exit 0
fi

# Convert platforms string to array
IFS=',' read -r -a platform_list <<< "$platforms"

pulled=""
while IFS= read -r i; do
    [ -z "${i}" ] && continue
    [[ "${i}" == "#"* ]] && continue

    for platform in "${platform_list[@]}"; do
        # Convert linux/amd64 to linux-amd64 for tagging
        arch_suffix=$(echo "$platform" | tr '/' '-')
        tagged_image="${i}-${arch_suffix}"

        if docker pull --platform="${platform}" "${i}"; then
            echo "Image pull success: ${i} (${platform})"
            # Tag with architecture suffix
            docker tag "${i}" "${tagged_image}"
            pulled="${pulled} ${tagged_image}"
        else
            if docker inspect "${tagged_image}" > /dev/null 2>&1; then
                pulled="${pulled} ${tagged_image}"
            else
                echo "Image pull failed: ${i} (${platform})"
            fi
        fi
    done
done < "${list}"

image_count=$(echo ${pulled} | wc -w | tr -d '[:space:]')
if [[ ${image_count} -eq 0 ]]; then
    echo "Error: No images were pulled successfully"
    exit 1
fi

echo "Creating ${images} with ${image_count} images"
if ! docker save ${pulled} | gzip --stdout > ${images}; then
    echo "Error: Failed to save images to ${images}"
    exit 1
fi
