#!/bin/bash
images="vcluster-images.tar.gz"
list="images.txt"
platforms="linux/amd64"
docker_args=""

usage () {
    echo "USAGE: $0 [--images vcluster-images.tar.gz] --registry my.registry.com:5000"
    echo "  [-l|--image-list path] text file with list of images; one image per line."
    echo "  [-i|--images path] tar.gz generated by docker save."
    echo "  [-r|--registry registry:port] target private registry:port."
    echo "  [-p|--platforms platforms] comma-separated platforms. (Default: linux/amd64)"
    echo "  [--insecure] use HTTP instead of HTTPS for registry communication."
    echo "  [-h|--help] Usage message"
}

while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -r|--registry)
        reg="$2"
        shift # past argument
        shift # past value
        ;;
        -l|--image-list)
        list="$2"
        shift # past argument
        shift # past value
        ;;
        -i|--images)
        images="$2"
        shift # past argument
        shift # past value
        ;;
        -p|--platforms)
        platforms="$2"
        shift # past argument
        shift # past value
        ;;
        --insecure)
        docker_args="--insecure"
        shift
        ;;
        -h|--help)
        help="true"
        shift
        ;;
        *)
        usage
        exit 1
        ;;
    esac
done

if [[ -z $reg ]]; then
    usage
    exit 1
fi
if [[ $help ]]; then
    usage
    exit 0
fi

if ! docker load --input ${images}; then
    echo "Error: Failed to load images from ${images}"
    exit 1
fi

# Convert platforms string to array
IFS=',' read -r -a platform_list <<< "$platforms"

# Build arch suffix list
arch_list=()
for platform in "${platform_list[@]}"; do
    arch_suffix=$(echo "$platform" | tr '/' '-')
    arch_list+=("${arch_suffix}")
done

# Enable experimental CLI for manifest commands
export DOCKER_CLI_EXPERIMENTAL=enabled

linux_images=()
while IFS= read -r i; do
    [ -z "${i}" ] && continue
    [[ "${i}" == "#"* ]] && continue

    linux_images+=("${i}");
done < "${list}"

for i in "${linux_images[@]}"; do
    [ -z "${i}" ] && continue
    [[ "${i}" == "#"* ]] && continue

    # trim ghcr.io & registry.k8s.io & quay.io & docker.io
    image_name=$(echo $i | sed 's/ghcr\.io\///')
    image_name=$(echo $image_name | sed 's/registry\.k8s\.io\///')
    image_name=$(echo $image_name | sed 's/quay\.io\///')
    image_name=$(echo $image_name | sed 's/docker\.io\///')

    target_image="${reg}/${image_name}"
    manifest_list=()

    # Push each architecture
    for arch_suffix in "${arch_list[@]}"; do
        source_tagged="${i}-${arch_suffix}"
        target_tagged="${target_image}-${arch_suffix}"

        # Check if the arch-specific image exists
        if docker inspect "${source_tagged}" > /dev/null 2>&1; then
            echo "Push ${source_tagged} as ${target_tagged}"
            docker tag "${source_tagged}" "${target_tagged}"
            if docker push "${target_tagged}"; then
                manifest_list+=("${target_tagged}")
            else
                echo "Error: Failed to push ${target_tagged}"
            fi
        else
            echo "Warning: ${source_tagged} not found, skipping"
        fi
    done

    # Create and push manifest list if we have at least one architecture
    if [[ ${#manifest_list[@]} -gt 0 ]]; then
        echo "Creating manifest ${target_image} with ${manifest_list[*]}"
        # Remove any existing manifest to avoid conflicts
        docker manifest rm "${target_image}" 2>/dev/null || true
        if ! docker manifest create ${docker_args} "${target_image}" "${manifest_list[@]}" --amend; then
            echo "Error: Failed to create manifest for ${target_image}"
            exit 1
        fi
        if ! docker manifest push "${target_image}" --purge ${docker_args}; then
            echo "Error: Failed to push manifest for ${target_image}"
            exit 1
        fi
    else
        echo "Warning: No architectures found for ${i}, skipping manifest creation"
    fi
done
