controlPlane:
  statefulSet:
    image:
      registry: ""
      repository: {{ .Repository }}
      tag: {{ .Tag }}
sync:
  fromHost:
    configMaps:
      enabled: true
      mappings:
        byName:
          "from-host-sync-test/*": "barfoo/*"
          "default/my.cm": "barfoo/cm-my"
          "": "my-new-ns"
          "/my-cm-4": "barfoo/my-cm-4"
          "/specific-cm": "my-virtual-namespace/specific-cm"
          "my-ns/to-be-deleted": "my-ns/to-be-deleted"
          "same-ns/*": "same-ns/*"
