sync:
  toHost:
    customResources:
      components.dapr.io:
        enabled: true
      subscriptions.dapr.io:
        enabled: true
      resiliencies.dapr.io:
        enabled: true
      configurations.dapr.io:
        enabled: true

experimental:
  multiNamespaceMode:
    enabled: true
