{{- if and .Values.isolation.enabled .Values.isolation.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ template "vcluster.name" . }}-limit-range
  namespace: {{ .Values.isolation.namespace | default .Release.Namespace }}
spec:
  limits:
  - default:
      {{- range $key, $val := .Values.isolation.limitRange.default }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    defaultRequest:
      {{- range $key, $val := .Values.isolation.limitRange.defaultRequest }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    type: Container
{{- end }}
