apiVersion: v1
kind: ServiceAccount
metadata:
  name: vc-workload-{{ template "vcluster.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcluster
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ template "vcluster.name" . }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{ toYaml .Values.serviceAccount.imagePullSecrets | indent 2 }}
{{- end }}
