name: Workflow Linting

on:
  pull_request:
    paths:
      - ".github/workflows/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  actionlint:
    permissions:
      contents: read
      pull-requests: write
    uses: loft-sh/github-actions/.github/workflows/actionlint.yaml@actionlint/v1
    with:
      reporter: github-pr-check
