name: Automatic backport action

on:
  pull_request_target:
    types: ["labeled", "closed"]

permissions:
  contents: read

jobs:
  backport:
    uses: loft-sh/github-actions/.github/workflows/backport.yaml@1103b80246219baef1cb52e69214278562ec7b0a # backport/v1
    secrets:
      gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
      linear-token: ${{ secrets.LINEAR_TOKEN }}
