name: Automatic backport action

on:
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  backport:
    uses: loft-sh/github-actions/.github/workflows/backport.yaml@36bd60efa4d72d6195f9222b67b1c633044bf90a # backport/v1
    secrets:
      gh-access-token: ${{ secrets.GH_ACCESS_TOKEN }}
