name: Cleanup github runner caches on closed pull requests

on:
  pull_request:
    types:
      - closed

permissions:
  actions: write

jobs:
  clean-github-cache:
    permissions:
      actions: write
    uses: loft-sh/github-actions/.github/workflows/clean-github-cache.yaml@clean-github-cache/v1
