---
name: Cleanup Head Charts

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

# make sure the pipeline is only running once
concurrency:
  group: cleanup-head-charts
  cancel-in-progress: false

jobs:
  cleanup:
    if: github.repository_owner == 'loft-sh' # do not run on forks
    uses: loft-sh/github-actions/.github/workflows/cleanup-head-charts.yaml@cleanup-head-charts/v1
    with:
      chart-name: vcluster-head
      chart-museum-url: https://charts.loft.sh
    secrets:
      chart-museum-user: ${{ secrets.CHART_MUSEUM_USER }}
      chart-museum-password: ${{ secrets.CHART_MUSEUM_PASSWORD }}
